'use client';
import { Box, Eye, EyeOff, Upload, Trash2 } from 'lucide-react';
import type { ReferenceModel } from '@/lib/model';
import type { AssetCache } from '@/lib/import-geometry';
import type { GizmoMode } from './model-view';
import TransformEditor from './transform-editor';
import NumberField from './number-field';
type Props={references:ReferenceModel[];assets:AssetCache;selectedId:string|null;onSelect:(id:string)=>void;onChange:(changes:Partial<ReferenceModel>)=>void;onDelete:()=>void;onImport:()=>void;onFolder:()=>void;busy:boolean;onGizmo:(mode:GizmoMode)=>void;onFit:()=>void};
export default function ReferencePanel(p:Props) {
  const selected=p.references.find(r=>r.id===p.selectedId),asset=selected?p.assets.get(selected.assetId):null;
  return <div className="reference-panel"><p className="form-hint">Bring your interior into the session and sketch on its faces or in the space around it.</p><button className="primary-button next-sketch" disabled={p.busy} onClick={p.onImport}><Upload size={15}/>{p.busy?'Reading model…':'Import geometry'}</button><button className="text-button" disabled={p.busy} onClick={p.onFolder}>Import model folder</button><p className="form-hint">GLB · glTF · OBJ · FBX. For glTF/OBJ, select the model, buffers, materials and textures together, or choose its folder. Files stay in this browser.</p>
    <div className="object-list">{p.references.map(r=><button className={'object-row '+(selected?.id===r.id?'selected':'')} key={r.id} onClick={()=>p.onSelect(r.id)}><Box size={16}/><span>{r.name}<small>{r.format.toUpperCase()} · {r.visible?'Visible':'Hidden'}</small></span></button>)}</div>
    {selected&&<div className="reference-properties"><label className="field-label" htmlFor="reference-name">REFERENCE MODEL</label><input id="reference-name" className="session-name" value={selected.name} maxLength={80} onChange={e=>{if(e.target.value.trim())p.onChange({name:e.target.value});}}/><div className="reference-actions"><button onClick={()=>p.onChange({visible:!selected.visible})}>{selected.visible?<EyeOff size={14}/>:<Eye size={14}/>} {selected.visible?'Hide model':'Show model'}</button><button onClick={p.onFit}>Fit session</button></div><p className="form-hint">{asset?.triangles.toLocaleString()} triangles · imported mesh reference</p><label className="field-label" htmlFor="model-units">SOURCE UNITS</label><select id="model-units" value={selected.unitScale} onChange={e=>p.onChange({unitScale:Number(e.target.value)})}>{![1,.01,.001,.3048,.0254].includes(selected.unitScale)&&<option value={selected.unitScale}>Native file units</option>}<option value={1}>Meters</option><option value={.01}>Centimeters</option><option value={.001}>Millimeters</option><option value={.3048}>Feet</option><option value={.0254}>Inches</option></select><div className="number-grid"><NumberField label="Model opacity" value={Math.round(selected.opacity*100)} min={5} max={100} step={5} unit="%" onChange={v=>p.onChange({opacity:v/100})}/></div><TransformEditor key={selected.id+JSON.stringify(selected.transform)} initial={selected.transform} onApply={transform=>p.onChange({transform})} onGizmo={p.onGizmo} disabled={!selected.visible}/><button className="text-button" onClick={()=>p.onChange({transform:{...selected.transform,rotation:[selected.transform.rotation[0]-90,selected.transform.rotation[1],selected.transform.rotation[2]]}})}>Rotate Z-up model to Y-up</button><button className="text-button remove-object" onClick={p.onDelete}><Trash2 size={14}/>Remove imported model</button></div>}
  </div>;
}
