'use client';
import { Check, Eye, EyeOff, Lock, Unlock, Plus, Trash2, ArrowRight } from 'lucide-react';
import type { Project, SketchGroup, Stroke, Transform } from '@/lib/model';
import { strokeGroup } from '@/lib/session';
import type { GizmoMode } from './model-view';
import TransformEditor from './transform-editor';
type Props={project:Project;activeGroupId:string;selectedIds:string[];onGroup:(id:string)=>void;onUpdateGroup:(id:string,changes:Partial<SketchGroup>)=>void;onNext:()=>void;onDeleteGroup:(id:string)=>void;onSelect:(ids:string[])=>void;onDelete:()=>void;onTransform:(t:Transform)=>void;onGizmo:(mode:GizmoMode)=>void;onMoveTo:(id:string)=>void;onUpdateStroke:(id:string,changes:Partial<Stroke>)=>void;onContinuePlane:()=>void};
export default function SketchSessionPanel(p:Props) {
  const group=p.project.groups.find(g=>g.id===p.activeGroupId)||p.project.groups[0],strokes=p.project.strokes.filter(s=>strokeGroup(p.project,s)===group.id),single=p.project.strokes.find(s=>p.selectedIds.length===1&&s.id===p.selectedIds[0]);
  return <div className="session-panel"><p className="form-hint">One session, all your ideas. Keep drawing, organize the ink, then continue with the next sketch.</p><div className="sketch-group-list">{p.project.groups.map(g=><div className={'sketch-group '+(g.id===group.id?'selected':'')} key={g.id}><button className="sketch-group-open" onClick={()=>p.onGroup(g.id)} aria-label={'Open sketch '+g.name}><span>{g.status==='ready'?<Check size={15}/>:<Plus size={15}/>}</span><span>{g.name}<small>{p.project.strokes.filter(s=>strokeGroup(p.project,s)===g.id).length} strokes · {g.status==='ready'?'Ready':'Drawing'}</small></span></button><button className="icon-button" aria-label={(g.visible?'Hide ':'Show ')+g.name} onClick={()=>p.onUpdateGroup(g.id,{visible:!g.visible})}>{g.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button><button className="icon-button" aria-label={(g.locked?'Unlock ':'Lock ')+g.name} onClick={()=>p.onUpdateGroup(g.id,{locked:!g.locked})}>{g.locked?<Lock size={13}/>:<Unlock size={13}/>}</button></div>)}</div>
    <label className="field-label" htmlFor="sketch-name">ACTIVE SKETCH</label><input id="sketch-name" aria-label="Sketch name" className="session-name" value={group.name} maxLength={80} onChange={e=>{if(e.target.value.trim())p.onUpdateGroup(group.id,{name:e.target.value});}}/><button className="primary-button next-sketch" onClick={p.onNext} disabled={p.project.groups.length>=100}>Finish & next sketch <ArrowRight size={15}/></button>
    <div className="stroke-list-heading"><span>{p.selectedIds.length} selected</span><button onClick={()=>p.onSelect(strokes.map(s=>s.id))}>Select all ink</button><button onClick={()=>p.onSelect([])}>None</button></div><div className="stroke-list">{strokes.map((s,i)=><label key={s.id}><input type="checkbox" aria-label={'Select '+(s.name||'Stroke '+(i+1))} checked={p.selectedIds.includes(s.id)} onChange={e=>p.onSelect(e.target.checked?[...p.selectedIds,s.id]:p.selectedIds.filter(id=>id!==s.id))}/><span>{s.name||'Stroke '+(i+1)}<small>{s.frame?.label||s.plane} · {s.points.length} points</small></span></label>)}{!strokes.length&&<p className="form-hint">Sketch on any plane. Each stroke stays ink until you choose what to do with the idea.</p>}</div>
    {single&&<><label className="field-label" htmlFor="stroke-name">STROKE NAME</label><input id="stroke-name" className="session-name" value={single.name||''} placeholder="Name this stroke" maxLength={80} onChange={e=>p.onUpdateStroke(single.id,{name:e.target.value.trim()||undefined})}/><button className="text-button" onClick={p.onContinuePlane}>Use this stroke’s plane</button></>}
    <TransformEditor key={p.selectedIds.join(',')} disabled={!p.selectedIds.length||group.locked||!group.visible} onApply={p.onTransform} onGizmo={p.onGizmo}/>
    {p.selectedIds.length>0&&<><label className="field-label" htmlFor="move-ink">ORGANIZE SELECTED INK</label><select id="move-ink" value="" disabled={group.locked} onChange={e=>p.onMoveTo(e.target.value)}><option value="">Move to another sketch…</option>{p.project.groups.filter(g=>g.id!==group.id&&!g.locked).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="text-button remove-object" disabled={group.locked} onClick={p.onDelete}><Trash2 size={14}/>Delete selected ink</button></>}
    <button className="text-button remove-object" disabled={group.locked} onClick={()=>p.onDeleteGroup(group.id)}><Trash2 size={14}/>Delete this sketch</button>
  </div>;
}
